version: '3.8'

services:
  sqlite:
    image: nouchka/sqlite3
    environment:
      - SQLITE_DATABASE=/db/sql_app.db
    volumes:
      - ./backend/db:/db

  backend:
    build: ./backend
    env_file:
      - .env
    depends_on:
      - sqlite
    volumes:
      - ./backend/db:/db
      - ./.env:/app/.env
    ports:
      - "8050:8050"
    command: ["sh", "-c", "alembic upgrade head && python create_user.py --username admin --password admin --email admin@admin && python main.py"]


  frontend:
    build: ./frontend
    depends_on:
      - backend
    environment:
      - VITE_BACKEND_URL=http://localhost:8050
    ports:
      - "3000:3000"
