"""history_upload

Revision ID: 0932ef3a59d6
Revises: 665cad4de0be
Create Date: 2024-06-15 13:24:41.337470

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0932ef3a59d6'
down_revision: Union[str, None] = '665cad4de0be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('processing_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('success_count', sa.Integer(), nullable=True),
    sa.Column('failure_count', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_processing_history_id'), 'processing_history', ['id'], unique=False)
    op.create_index(op.f('ix_processing_history_status'), 'processing_history', ['status'], unique=False)
    op.add_column('file_uploads', sa.Column('history_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_file_uploads_history_id'), 'file_uploads', ['history_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_file_uploads_history_id'), table_name='file_uploads')
    op.drop_column('file_uploads', 'history_id')
    op.drop_index(op.f('ix_processing_history_status'), table_name='processing_history')
    op.drop_index(op.f('ix_processing_history_id'), table_name='processing_history')
    op.drop_table('processing_history')
    # ### end Alembic commands ###
