"""Initial migration

Revision ID: 7fa106924cb9
Revises: 
Create Date: 2024-06-12 11:50:48.422113

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7fa106924cb9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('file_uploads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(), nullable=True),
    sa.Column('size', sa.Integer(), nullable=True),
    sa.Column('rows', sa.Integer(), nullable=True),
    sa.Column('upload_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_file_uploads_filename'), 'file_uploads', ['filename'], unique=False)
    op.create_index(op.f('ix_file_uploads_id'), 'file_uploads', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_file_uploads_id'), table_name='file_uploads')
    op.drop_index(op.f('ix_file_uploads_filename'), table_name='file_uploads')
    op.drop_table('file_uploads')
    # ### end Alembic commands ###
