"""history_size

Revision ID: e30f571ecef0
Revises: 0932ef3a59d6
Create Date: 2024-06-15 13:49:47.088895

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e30f571ecef0'
down_revision: Union[str, None] = '0932ef3a59d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('processing_history', sa.Column('size', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('processing_history', 'size')
    # ### end Alembic commands ###
